repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "Mod Maven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Create Maven"
        url = "https://maven.createmod.net"
    }
    maven {
        name = "Ryanhcode Maven"
        url = "https://maven.ryanhcode.dev/releases"
    }
    maven {
        name = "Bawnorton Maven"
        url = "https://maven.bawnorton.com/releases"
    }
    maven {  // Registrate
        name = "Ithundxr Maven"
        url = "https://maven.ithundxr.dev/snapshots"
    }
    maven { // Veil
        name = 'BlameJared Maven'
        url = 'https://maven.blamejared.com'
    }
    maven { // CC Tweaked
        name = "SquidDev Maven"
        url = "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }
}
