dependencies {
    implementation(libs.bundles.anvillib)
    jarJar(libs.bundles.anvillib)

    implementation(libs.bundles.mixinsquared)
    jarJar(libs.mixinsquared)

    compileOnly libs.jsr305
    compileOnly libs.jeiApi
    runtimeOnly libs.jei

    compileOnly(libs.registrate)
    implementation(libs.bundles.simulated) {
        exclude group: "com.tterrag.registrate"
        exclude group: "cc.tweaked"
    }

    compileOnly libs.bundles.ccTweakedApi
    runtimeOnly libs.ccTweaked
}
