# JVM Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
java_version=21
## Environment Properties
minecraft_version_range=[1.21.1,1.21.2)
neo_version_range=[21,)
loader_version_range=[4,)
modrinth_id=S1dDBOGZ
curseforge_id=1522614
upload=true
## Mod Properties
mod_id=gravitation
mod_name=Gravitation
mod_license=GNU LGPL 3.0
mod_version=0.0.3
maven_group=dev.dubhe.gravitation
mod_authors=Gugle
mod_description=
